export const CREATE_BOARD = 'CREATE_BOARD';
export const GET_BOARDS = 'GET_BOARDS';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';

export const CREATE_LOCATION = 'CREATE_LOCATION';
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const CREATE_STAFF_MEMBER = 'CREATE_STAFF_MEMBER';
export const GET_STAFF_MEMBERS = 'GET_STAFF_MEMBERS';
export const UPDATE_STAFF_MEMBER = 'UPDATE_STAFF_MEMBER';
